### ISSUE TITLE
Issue when creating portable version

### ISSUE THREAD

**Issue by CyrilleB79** [nvda-es/updateChannel#5]
Issue first opened against NVDA (https://github.com/nvaccess/nvda/issues/13786) but Update Channel Selector was discovered to cause the issue.

### STR
* On NVDA 2022.1, install update channel selector. The update channel is set to "Default" (I thought to have it on "Stable, rc and beta" but this was not the case actually)
* Download last alpha from NVDA (nvda_snapshot_alpha-25538,f3445949.exe)
* Start the launcher and create a portable copy.
* Launch the portable copy or check its content

### Actual result
* The portable copy crashes
* The folders "lib", "lib64" and "libArm64" are all empty

### Actual result
* The portable copy should start without any problem
* The whole portable copy should be created: the folders "lib", "lib64" and "libArm64" should contain a folder with files.

**Comment by jmdaweb** [comment]
Hi,
This is directly caused by workaround for issue #3. The value of `versionInfo.version` is patched, the launcher looks for DLL files for the patched version, thush no DLL files are copied to the portable copy.
This workaround was made because NV Access won't apply solutions for the new use cases provided by this add-on on their servers. Any suggestions are welcome, I don't know what to do to fix this issue.

**Comment by CyrilleB79** [comment]
I do not know in detail the code. Maybe patching the versionInfo variables could be done only when there are update check or update requests and the values restored when the update is finished? This would allow to avoid to have it patched during the whole time (in __init__ and terminate methods).

If it is not possible, at least documenting clearly this side effect should be done in the documentation. If there are other side effects, they should also be documented.
In this case also, you could also disable the creation of portable versions, or issue a message to indicate people to disable the add-on before creating a portable versions.
